# DATABASE_USER = 'root'
# DATABASE_PASSWORD = '1234'
# DATABASE_HOST = '127.0.0.1'
# DATABASE_PORT = '3306'
# DATABASE_DB = 'new_wedding'

DATABASE_USER = 'wedding1'
DATABASE_PASSWORD = 'wedding1'
DATABASE_HOST = 'wedding1.cgk1rrf3qjsz.ap-northeast-2.rds.amazonaws.com'
DATABASE_PORT = '3306'
DATABASE_DB = 'new_wedding'